### ISSUE TITLE
Tag details on right hand side for previously viewed project is shown

### ISSUE THREAD

**Issue by matt-thurling** [orionhealth/XBDD#330]
### Steps to Reproduce:
1) Go to a project
2) Select one of the tags so the right hand side shows tests and their statuses
3) Click the browser back button
4) Select a different project
### Expected Result:
The different project loads with its tags shown on the left hand side, and the right-hand side is clear because no tags have been selected yet.
### Actual Result
The different project loads with its tags shown on the left hand side, but the right hand side shows the the tests and statuses from the previous project (i.e. what it showed in Step 2 above).

**Comment by ryan-rushton** [comment]
Need to clear the feature.selected redux state when choosing a build to look at or when loading the feature container.
