### ISSUE TITLE
Show date next to build number

### ISSUE THREAD

**Issue by steveswinsburg** [orionhealth/XBDD#409]
Otherwise we don't know when that build was from
![Screen Shot 2020-09-22 at 3 58 08 pm](https://user-images.githubusercontent.com/129129/93848285-7db95200-fcec-11ea-9d62-2182353e3378.png)

**Comment by ahnaf17** [comment]
Seems like mongodb doesn't have info about the build datetime. One implementation could be to save the datetime everytime new build info gets stored in the database.
