### ISSUE TITLE
need 'configuring' section in the install guide

### ISSUE THREAD

**Issue by steveswinsburg** [orionhealth/XBDD#52]
To document the init params like the phantomjs ones.
ref:
https://github.com/orionhealth/XBDD/blob/cccabb050511cf3dd890176de79347c751e177a5/src/main/java/xbdd/webapp/resource/feature/PrintPDF.java

**Comment by ryan-rushton** [comment]
I think this is covered in the latest stuff so far, I don't think we will get back to change the old version. Reopen if you think otherwise
